// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_q355yCa_tnsOx0flyP4ZbyjA2Hw8NkU',
    appId: '1:880099449018:web:e0c2d95bc3507774448a83',
    messagingSenderId: '880099449018',
    projectId: 'circolapp-6b344',
    authDomain: 'circolapp-6b344.firebaseapp.com',
    storageBucket: 'circolapp-6b344.firebasestorage.app',
    measurementId: 'G-JT3FKT4BBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDobox-iv6FkrlFeuLluOlnMVwRCBCBEbM',
    appId: '1:880099449018:android:4980cb8423c8d96e448a83',
    messagingSenderId: '880099449018',
    projectId: 'circolapp-6b344',
    storageBucket: 'circolapp-6b344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD10cf6tKeKjM73Oh9HrRfyYpj60anHUFA',
    appId: '1:880099449018:ios:4dba3297cb6a1163448a83',
    messagingSenderId: '880099449018',
    projectId: 'circolapp-6b344',
    storageBucket: 'circolapp-6b344.firebasestorage.app',
    androidClientId: '880099449018-ldhpccdp6trmqmmqut3pbsmhknu1c5fu.apps.googleusercontent.com',
    iosClientId: '880099449018-t1i5f8s0jc2brhe9t8olcag95la7kn1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.circolAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD10cf6tKeKjM73Oh9HrRfyYpj60anHUFA',
    appId: '1:880099449018:ios:4dba3297cb6a1163448a83',
    messagingSenderId: '880099449018',
    projectId: 'circolapp-6b344',
    storageBucket: 'circolapp-6b344.firebasestorage.app',
    androidClientId: '880099449018-ldhpccdp6trmqmmqut3pbsmhknu1c5fu.apps.googleusercontent.com',
    iosClientId: '880099449018-t1i5f8s0jc2brhe9t8olcag95la7kn1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.circolAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_q355yCa_tnsOx0flyP4ZbyjA2Hw8NkU',
    appId: '1:880099449018:web:c707ca77ae246025448a83',
    messagingSenderId: '880099449018',
    projectId: 'circolapp-6b344',
    authDomain: 'circolapp-6b344.firebaseapp.com',
    storageBucket: 'circolapp-6b344.firebasestorage.app',
    measurementId: 'G-6YR2D2MD0Q',
  );
}
